### ISSUE TITLE
Question: Deploying without cloudflare

### ISSUE THREAD

**Issue by bgervan** [jamsocket/y-sweet#228]
Hello, 

Is it possible to deploy it with docker without cloudflare? Or is it on the roadmap?

**Comment by paulgb** [comment]
Hi Benjamin,

It's possible now with the Docker image: https://github.com/jamsocket/y-sweet/pkgs/container/y-sweet

But there are currently a couple of issues with using that for more than a dev server:
- You can only run one instance, it's not horizontally scalable.
- It doesn't currently unload documents when they are no longer in use.

I'm planning to integrate with https://plane.dev which would solve both of those. It's on the roadmap, but I don't have an ETA yet.

**Comment by paulgb** [comment]
These issues are now fixed thanks to @rbtying's work! There's also now a simple reverse proxy setup that could be adapted for a single-node production setup (https://github.com/jamsocket/y-sweet/tree/main/deploy). I'm closing this since that work is done, but feel free to follow up with other questions.
