### ISSUE TITLE
Might make sense to run the dev server in single-threaded moe

### ISSUE THREAD

**Issue by rbtying** [jamsocket/y-sweet#236]
It looks like (according to https://github.com/y-crdt/y-crdt/issues/373), and also observations IRL, the `Drop` implementation for yrs Doc objects is not thread-safe.

Since it's unlikely that we're CPU-bound in practice, perhaps just run Tokio in single-threaded mode?

**Comment by paulgb** [comment]
Hmm, I'll need to comb through the code a bit, but I don't think we actually rely on any thread safety of Yrs since we use an `RwLock` to gate mutations of `Awareness`. Awareness does `unsafe impl {Send, Sync}`, but we don't actually use them so I've opened a PR to remove them (#241).

But if you're running into issues from your branch, it does seem like that assumption is wrong.

**Comment by rbtying** [comment]
Ah, you'd think so... but actually the issue is that yrs`Subscription` shouldn't implement `Send` right now I believe -- its `Drop` implementation doesn't internally acquire locks to ensure clean state. `RwLock` only helps make `Send`s `Sync`. 

It's possible this is fixed in yrs 0.19; it looks lke they changed up a bunch of how the reference stuff works. Will need to test

**Comment by paulgb** [comment]
Ah gotcha, that makes sense. I agree that switching to a single-thread runtime seems like the most sensible approach, and we can reevaluate when yrs fixes the underlying issue.

**Comment by rbtying** [comment]
OK I played with yrs 0.19 - it doesn't exhibit the same issue, and yrs maintainer says that they reworked how observers worked between 0.17 and 0.19. So perhaps we do that instead

**Comment by paulgb** [comment]
That's great news! I'm on board with that.

**Comment by rbtying** [comment]
Closed with #243
