### ISSUE TITLE
Pass a callback to get clientToken

### ISSUE THREAD

**Issue by scottrblock** [jamsocket/y-sweet#253]
Hi there, thanks for the work on this project.

What I'd like to do is pass a function to `createYjsProvider` to get the `clientToken`, instead of passing it as a string.

This allows the provider to be initially created and passed to wherever it needs to go without having to wait for an http request for the token until later.

This is similar to how y-partykit works - https://github.com/partykit/partykit/blob/main/packages/y-partykit/src/provider.ts#L568-L580

This looks like a pretty straightforward change, happy to take an initial stab at it, but figured I'd post it here first.

**Comment by paulgb** [comment]
I like this, will do.

**Comment by paulgb** [comment]
After making an attempt at this, I realized it's more involved than I expected. That said, it fits in nicely with a provider rewrite that is on the roadmap now. I'm going to leave this open, but it will be part of the larger rewrite effort.

**Comment by rolyatmax** [comment]
`v0.4.0` has changed [the `createYjsProvider` interface](https://docs.y-sweet.dev/functions/_y_sweet_client.createYjsProvider.html). It now takes an `authEndpoint` argument which is either the `string` of an endpoint to hit to get a `clientToken`, or you can pass a function that returns a `clientToken`. Note: this function may be called again if the current token expires, so it's best if the endpoint/function goes through the flow of getting a new client token from the y-sweet server instead of using a cached token.

I'm currently working on writing the docs for this change, but here's an example:

```ts
const doc = new Y.Doc()
const docId = 'my-doc-id'
const provider = await createYjsProvider(doc, docId, async () => {
  const response = await fetch(`/my-api/auth?doc=${docId}`)
  const data = await response.json()
  return data.clientToken
})
```
