### ISSUE TITLE
Run on Google Cloud Run

### ISSUE THREAD

**Issue by okatrppr** [jamsocket/y-sweet#359]
Since it use docker also, can it run on Google Cloud Run?

**Comment by paulgb** [comment]
Just tested it, it works!

The main caveat here is that you can only scale to one instance, which on GCR gives you up to 1000 concurrent connections (that's a hard limit; the compute resources may only be able to handle less). The reason for this is that like many realtime sync engines, Y-Sweet stores the document in-memory on the server when it is active. If you have multiple servers, two users editing the same document could be connected to two different versions of the document in memory.

Here are the steps I took to deploy it:

I had to rebuild the image with Google Cloud Build because they (annoyingly) do not support `ghcr.io` images.

For container config, I did this:

<img width="786" alt="image" src="https://github.com/user-attachments/assets/2927895c-d75e-4af9-a2c5-53f5139e8dc9" />

Note that this doesn't connect any storage; you'll want to do that with the `variables & secrets` tab to persist data, otherwise it will just do ephemeral sync.

Set maximum concurrency to 1000:

<img width="817" alt="image" src="https://github.com/user-attachments/assets/d1096461-e156-492a-ae22-40b027f20850" />

Set maximum number of instances to 1:

<img width="804" alt="image" src="https://github.com/user-attachments/assets/7aaa02ac-a417-40c9-8b08-25d7f9958ed6" />

Once you need to scale beyond 1000 concurrent connections, [Jamsocket](https://jamsocket.com/) is like Google Cloud Run but with a stateful routing layer designed to avoid the 1 instance limit, and has [native support for Y-Sweet](https://jamsocket.com/y-sweet) with a 10GB free tier.

**Comment by okatrppr** [comment]
Thank you for very detail explanation @paulgb
